// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycyprrojnpactiebhqkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeXBycm9qbnBhY3RpZWJocWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY3NjQsImV4cCI6MjA2NjM1Mjc2NH0.Mw2Zab3BH8oxjhlzViFtQazzZiqlnh_QLuqc78NptWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);